### ISSUE TITLE
I fixed it!

### ISSUE THREAD

**Issue by VMI1994** [cowboysdude/MMM-Nascar#3]
I had previously asked you to take a look at MMM-Nascar to fix it.  After a little fiddling(I don't know java, just a very little BASH), I figured out what broke it.

1. I deleted all the entries in the Driver Table in the MMM-Nascar.js file(People who follow Nascar don't need the car number and they change every season so the table would need constant updating)
2. Nascar moved the referenced url in node_helper.js.  The proper url is:
  "https://cf.nascar.com/cacher/"+year+"/1/final/1-drivers-points.json"

thanks for the module, my friends and I really love it!

**Comment by cowboysdude** [comment]
Life keeps me so busy I rarely look at github unless I have time....... Thank you for pull requests!!!!!!!
